### ISSUE TITLE
How to change the hooks route

### ISSUE THREAD

**Issue by siba2893** [esbanarango/zapier-REST-hooks#1]
I need the hook create and delete to be in the following route: 

/api/hooks/ <- Create

/api/hooks/:id <- Destroy

But Im not able to achieve this, for some reason.

I tried making this change:

 mount ZapierRestHooks::Engine, at: '/api/hooks' but it didn't work

**Comment by esbanarango** [comment]
Hello @siba2893 Could you share your `routes.rb`.

**Comment by siba2893** [comment]
<img width="447" alt="captura de pantalla 2017-03-21 a las 09 33 19" src="https://cloud.githubusercontent.com/assets/2425158/24155445/78c0b830-0e19-11e7-96fd-c5f76d163e7d.png">

**Comment by esbanarango** [comment]
Thank you @siba2893. Try adding a namespace and mounting the Engine under it, like this:

```ruby
namespace :api do
  mount ZapierRestHooks::Engine, at: '/hooks'
end
````

Let me know if that works.

**Comment by siba2893** [comment]
<img width="801" alt="captura de pantalla 2017-03-21 a las 09 38 53" src="https://cloud.githubusercontent.com/assets/2425158/24155727/3ceb10fc-0e1a-11e7-99af-e7bf1fbd3349.png">

Rake routes still coming out like /hooks instead of /api/hooks

**Comment by esbanarango** [comment]
@siba2893 did you figure this out? I'm closing this, feel free to re-open it if you still having issues.
