### ISSUE TITLE
doesnt work on rails 5.x?

### ISSUE THREAD

**Issue by jtoy** [esbanarango/zapier-REST-hooks#8]
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.0.6)

    zapier_rest_hooks was resolved to 0.0.1, which depends on
      rails (>= 4.2.3, ~> 4.2.3)

**Comment by esbanarango** [comment]
Hello @jtoy, You can use master now. We're waiting to release a new version once https://github.com/chrisk/fakeweb/issues/57 is closed.
